<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.1 (Python 3.11.0 on win32)" generated="20230926 20:25:39.727" rpa="false" schemaversion="3">
<suite id="s1" name="Singlepage" source="c:\qa\Calculadora_RobotFrameworkSinglePage\resources\singlepage.robot">
<test id="s1-t1" name="Calculo com numeros inteiros - divisao" line="82">
<kw name="Dado que estou com a calculadora aberta">
<kw name="Abrir o app [no dispositivo: pixel4]" library="base" sourcename="Abrir o app [no dispositivo: ${avd}]">
<kw name="Get Current Date" library="DateTime">
<var>${data_atual}</var>
<arg>result_format=%d-%m-%Y</arg>
<doc>Returns current local or UTC time with an optional increment.</doc>
<msg timestamp="20230926 20:25:40.623" level="INFO">${data_atual} = 26-09-2023</msg>
<status status="PASS" starttime="20230926 20:25:40.621" endtime="20230926 20:25:40.637"/>
</kw>
<kw name="Set Suite Variable" library="BuiltIn">
<arg>${titulo}</arg>
<arg>${TEST NAME}</arg>
<doc>Makes a variable available everywhere within the scope of the current suite.</doc>
<msg timestamp="20230926 20:25:40.648" level="INFO">${titulo} = Calculo com numeros inteiros - divisao</msg>
<status status="PASS" starttime="20230926 20:25:40.638" endtime="20230926 20:25:40.649"/>
</kw>
<kw name="Create Directory" library="OperatingSystem">
<arg>evidencias\\${data_atual}</arg>
<doc>Creates the specified directory.</doc>
<msg timestamp="20230926 20:25:40.651" level="INFO" html="true">Directory '&lt;a href="file://C:\qa\Calculadora_RobotFrameworkSinglePage\evidencias\26-09-2023"&gt;C:\qa\Calculadora_RobotFrameworkSinglePage\evidencias\26-09-2023&lt;/a&gt;' already exists.</msg>
<status status="PASS" starttime="20230926 20:25:40.650" endtime="20230926 20:25:40.651"/>
</kw>
<kw name="Exibir no console Abrir o app Calculadora ${appPackage}" library="base" sourcename="Exibir no console ${mensagem}">
<kw name="Log To Console" library="BuiltIn">
<arg>${mensagem}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20230926 20:25:40.653" endtime="20230926 20:25:40.664"/>
</kw>
<status status="PASS" starttime="20230926 20:25:40.652" endtime="20230926 20:25:40.665"/>
</kw>
<kw name="Open Application" library="AppiumLibrary">
<arg>${REMOTE_URL}</arg>
<arg>platformName=${platformName}</arg>
<arg>automationName=${automationName}</arg>
<arg>deviceName=${deviceName}</arg>
<arg>appPackage=${appPackage}</arg>
<arg>appActivity=${appActivity}</arg>
<arg>avd=${avd}</arg>
<arg>deviceOrientation=${deviceOrientation}</arg>
<arg>ensureWebviewsHavePages=${ensureWebviewsHavePages}</arg>
<arg>nativeWebScreenshot=${nativeWebScreenshot}</arg>
<arg>newCommandTimeout=${newCommandTimeout}</arg>
<arg>connectHardwareKeyboard=${connectHardwareKeyboard}</arg>
<arg>avdReadyTimeout=${avdReadyTimeout}</arg>
<arg>avdLaunchTimeout=${avdLaunchTimeout}</arg>
<arg>noSign=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230926 20:25:51.183" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230926 20:25:51.182" endtime="20230926 20:25:51.193"/>
</kw>
<msg timestamp="20230926 20:25:51.198" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230926 20:25:51.211" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: logger_js_1.default.err is not a function
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: logger_js_1.default.err is not a function
    at getResponseForW3CError (C:\Users\Luciano\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1092:9)
    at asyncHandler (C:\Users\Luciano\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:491:57)</msg>
<status status="FAIL" starttime="20230926 20:25:40.665" endtime="20230926 20:25:51.214"/>
</kw>
<status status="FAIL" starttime="20230926 20:25:40.620" endtime="20230926 20:25:51.215"/>
</kw>
<kw name="Wait Until Element Is Visible" library="AppiumLibrary">
<arg>${texto_resultado}</arg>
<arg>15</arg>
<doc>Waits until element specified with `locator` is visible.</doc>
<status status="NOT RUN" starttime="20230926 20:25:51.216" endtime="20230926 20:25:51.217"/>
</kw>
<status status="FAIL" starttime="20230926 20:25:40.619" endtime="20230926 20:25:51.217"/>
</kw>
<kw name="E informo um valor (22)" sourcename="E informo um valor (${var_valor1})">
<status status="NOT RUN" starttime="20230926 20:25:51.267" endtime="20230926 20:25:51.267"/>
</kw>
<kw name="E escolho uma operacao (/)" sourcename="E escolho uma operacao (${oper})">
<status status="NOT RUN" starttime="20230926 20:25:51.374" endtime="20230926 20:25:51.375"/>
</kw>
<kw name="E informo um segundo valor (5)" sourcename="E informo um segundo valor (${var_valor2})">
<status status="NOT RUN" starttime="20230926 20:25:51.379" endtime="20230926 20:25:51.379"/>
</kw>
<kw name="Quando aciono a opcao igual">
<status status="NOT RUN" starttime="20230926 20:25:51.380" endtime="20230926 20:25:51.381"/>
</kw>
<kw name="Entao o resultado do calculo deve ser exibido">
<status status="NOT RUN" starttime="20230926 20:25:51.382" endtime="20230926 20:25:51.382"/>
</kw>
<doc>Testes com calculos de divisao de numeros inteiros</doc>
<tag>divisao</tag>
<tag>inteiros</tag>
<status status="FAIL" starttime="20230926 20:25:40.617" endtime="20230926 20:25:51.384">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: logger_js_1.default.err is not a function
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: logger_js_1.default.err is not a function
    at getResponseForW3CError (C:\Users\Luciano\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1092:9)
    at asyncHandler (C:\Users\Luciano\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:491:57)</status>
</test>
<kw name="Close Application" library="AppiumLibrary" type="TEARDOWN">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230926 20:25:51.392" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230926 20:25:51.391" endtime="20230926 20:25:51.396"/>
</kw>
<msg timestamp="20230926 20:25:51.402" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230926 20:25:51.404" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230926 20:25:51.390" endtime="20230926 20:25:51.407">No application is open</status>
</kw>
<status status="FAIL" starttime="20230926 20:25:39.739" endtime="20230926 20:25:51.408">Suite teardown failed:
No application is open</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">divisao</stat>
<stat pass="0" fail="1" skip="0">inteiros</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Singlepage">Singlepage</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230926 20:25:51.198" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230926 20:25:51.402" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
